modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="dtru" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dynamic Trees for Regions Unexplored" #mandatory
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BOP.json?raw=true" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/dtru" #optional
logoFile="" #optional
credits="ferreusveritas, hawksteak" #optional
authors="mangoose, Max Hyper" #optional

description='''
Compatibility Mod between Dynamic trees and Regions Unexplored
'''

[[dependencies.dtru]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dtru]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtru]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.0-BETA3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtru]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.3.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtru]]
    modId="regions_unexplored"
    mandatory=true
    versionRange="[0.5.5,)"
    ordering="AFTER"
    side="BOTH"
